export const Degrees = ["B.Tech","B.Pharm","B.Sc","B.A","B.Com","M.A","M.COM"]
export const BtechBranchs = [{id:"ECE",name:"ELECTRONICS AND COMMUNICATION ENGINEERING"}]
export const BA = ["English","English Literature","Fine Arts","Psychology","Archaeology","Social Work"]
export const BCom = ["Accounting & Commerce","Finance.","Sales & Marketing.","Auditing and Control.","Transport and Logistics","Supply Chain Management.","Human Resources.","International Accounting."]
export const Bsc = ["Agriculture.","Biotechnology.","Zoology.","Clinical Research & Healthcare Management.","Forestry.","Microbiology.","Nursing.","B.Sc. Physiotherapy."]
export const MA = [ "Specialisations","Psychology","Communication Studies","Philosophy","Archaeology", "Sociology","Religious Studies","Geography","Literature"]
export const Mcom   = ["Banking", "Finance","Banking and Finance","Finance & Control","Marketing","E-Commerce","Business Management","Computer Application"]